### ISSUE TITLE
支持移动版

### ISSUE THREAD

**Issue by vivaxy** [wheatma/grid-trade-helper#14]
方便手机查看和操作

**Comment by wheatma** [comment]
微信小程序"网格交易助手"的名字已经被占了🙃

**Comment by vivaxy** [comment]
@wheatma 可以让网页版支持手机浏览器吗？

**Comment by wheatma** [comment]
#15 
[https://grid.wheat.now.sh/](https://grid.wheat.now.sh/) 优化手机样式
